# Generated by Django 4.2.6 on 2023-12-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0005_rename_text_review_count_book_text_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_desired',
            field=models.BooleanField(default=False, help_text='Is this book desired?'),
        ),
    ]
