# Generated by Django 4.2.6 on 2023-10-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=1, upload_to='book_covers/'),
            preserve_default=False,
        ),
    ]
