# Generated by Django 4.2.6 on 2023-12-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0004_remove_userprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='text_review_count',
            new_name='text_reviews_count',
        ),
    ]
