# Generated by Django 4.2.6 on 2023-12-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0006_book_is_desired'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
