# Generated by Django 4.2.6 on 2023-10-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HalamanInformasiBuku', '0004_loan_address_loan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='tanggal_pinjam',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
