# Generated by Django 4.2.4 on 2023-12-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HalamanReview', '0002_rename_comment_review_review_remove_review_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviewbook',
            name='total_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
