# Generated by Django 4.2.4 on 2023-12-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HalamanReview', '0003_alter_review_rating_alter_reviewbook_total_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewbook',
            name='total_review',
            field=models.IntegerField(default=0),
        ),
    ]
