# Generated by Django 4.2.6 on 2023-10-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HalamanInformasiBuku', '0003_remove_loan_name_loan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
